# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdmoney',
            name='paid',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
